### ISSUE TITLE
Some Questions about Compilation

### ISSUE THREAD

**Issue by wkindling** [sueda/eol-cloth#1]
Hi! 
Recently I am trying to implement your paper. So I ran your code on my own laptop. However, the result seems kind of strange and rough, which is different from the pictures in paper. Here is the screenshot. Is it correct? 
![screenshot](https://user-images.githubusercontent.com/23055417/57980154-bfcbe700-7a59-11e9-8440-9c2483a34474.jpg) 
Also, it seems that something goes wrong in the file 'simulationSettings.json'. My editor reports error on Line 92. I think you may forget to comment out the string "The". 
Thanks in advance for your help.

**Comment by weidnern** [comment]
Hey there!
The output you get from the code is never going to look like the paper figures unfortunately, because those figures were post processed in Blender. That's the purpose of the export functions. I also believe I left the example setups at a significantly smaller resolution so someone trying to use them could see how the program works at a reasonable viewing speed. The cloth resolutions used in the paper take much longer to sim, but are easily set with the resolution setting in the json. 
If that's a bug I can try and look into it when I get the time. Does "something foes wrong with the file" mean it crashed when trying to load, or something else?

**Comment by wkindling** [comment]
Thx for your attention. 
Actually it will indeed crash when trying to load the 'simulationSettings.json', and the error report is as follows:

```
Error reading file: simulationSettings.json

* Line 1, Column 3044
  Missing '}' or object member name
```
After I comment out Line 92, it gets to work.
